/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitarContaRouteImport } from './routes/solicitar-conta'
import { Route as SolicitarAcessoPainelRouteImport } from './routes/solicitar-acesso-painel'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PaineisRouteImport } from './routes/paineis'
import { Route as DadosAbertosRouteImport } from './routes/dados-abertos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaineisIdRouteImport } from './routes/paineis_.$id'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'

const SolicitarContaRoute = SolicitarContaRouteImport.update({
  id: '/solicitar-conta',
  path: '/solicitar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarAcessoPainelRoute = SolicitarAcessoPainelRouteImport.update({
  id: '/solicitar-acesso-painel',
  path: '/solicitar-acesso-painel',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaineisRoute = PaineisRouteImport.update({
  id: '/paineis',
  path: '/paineis',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosAbertosRoute = DadosAbertosRouteImport.update({
  id: '/dados-abertos',
  path: '/dados-abertos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaineisIdRoute = PaineisIdRouteImport.update({
  id: '/paineis_/$id',
  path: '/paineis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/dados-abertos': typeof DadosAbertosRoute
  '/paineis': typeof PaineisRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/solicitar-acesso-painel': typeof SolicitarAcessoPainelRoute
  '/solicitar-conta': typeof SolicitarContaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/reset': typeof AuthResetRoute
  '/paineis/$id': typeof PaineisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/dados-abertos': typeof DadosAbertosRoute
  '/paineis': typeof PaineisRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/solicitar-acesso-painel': typeof SolicitarAcessoPainelRoute
  '/solicitar-conta': typeof SolicitarContaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/reset': typeof AuthResetRoute
  '/paineis/$id': typeof PaineisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/dados-abertos': typeof DadosAbertosRoute
  '/paineis': typeof PaineisRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/solicitar-acesso-painel': typeof SolicitarAcessoPainelRoute
  '/solicitar-conta': typeof SolicitarContaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/reset': typeof AuthResetRoute
  '/paineis_/$id': typeof PaineisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/dados-abertos'
    | '/paineis'
    | '/painel'
    | '/perfil'
    | '/sobre'
    | '/solicitar-acesso-painel'
    | '/solicitar-conta'
    | '/admin/usuarios'
    | '/auth/reset'
    | '/paineis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/dados-abertos'
    | '/paineis'
    | '/painel'
    | '/perfil'
    | '/sobre'
    | '/solicitar-acesso-painel'
    | '/solicitar-conta'
    | '/admin/usuarios'
    | '/auth/reset'
    | '/paineis/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/dados-abertos'
    | '/paineis'
    | '/painel'
    | '/perfil'
    | '/sobre'
    | '/solicitar-acesso-painel'
    | '/solicitar-conta'
    | '/admin/usuarios'
    | '/auth/reset'
    | '/paineis_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  ContatoRoute: typeof ContatoRoute
  DadosAbertosRoute: typeof DadosAbertosRoute
  PaineisRoute: typeof PaineisRoute
  PainelRoute: typeof PainelRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
  SolicitarAcessoPainelRoute: typeof SolicitarAcessoPainelRoute
  SolicitarContaRoute: typeof SolicitarContaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  PaineisIdRoute: typeof PaineisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitar-conta': {
      id: '/solicitar-conta'
      path: '/solicitar-conta'
      fullPath: '/solicitar-conta'
      preLoaderRoute: typeof SolicitarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar-acesso-painel': {
      id: '/solicitar-acesso-painel'
      path: '/solicitar-acesso-painel'
      fullPath: '/solicitar-acesso-painel'
      preLoaderRoute: typeof SolicitarAcessoPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paineis': {
      id: '/paineis'
      path: '/paineis'
      fullPath: '/paineis'
      preLoaderRoute: typeof PaineisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-abertos': {
      id: '/dados-abertos'
      path: '/dados-abertos'
      fullPath: '/dados-abertos'
      preLoaderRoute: typeof DadosAbertosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paineis_/$id': {
      id: '/paineis_/$id'
      path: '/paineis/$id'
      fullPath: '/paineis/$id'
      preLoaderRoute: typeof PaineisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BuscarRoute: BuscarRoute,
  ContatoRoute: ContatoRoute,
  DadosAbertosRoute: DadosAbertosRoute,
  PaineisRoute: PaineisRoute,
  PainelRoute: PainelRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
  SolicitarAcessoPainelRoute: SolicitarAcessoPainelRoute,
  SolicitarContaRoute: SolicitarContaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  PaineisIdRoute: PaineisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
